import { useState, useRef, type FormEvent } from 'react';
import { ArrowUpRight, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { submitEnquiry } from '@/lib/enquiry.functions';
export function ContactForm() {
 const [state, setState] = useState<'idle'|'sending'|'success'|'error'>('idle'); const [error, setError] = useState(''); const key = useRef('');
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); if (!key.current) key.current = crypto.randomUUID(); setState('sending'); setError(''); try { await submitEnquiry({ data: { name: String(data.get('name')), company: String(data.get('company')), country: String(data.get('country')), email: String(data.get('email')), phone: String(data.get('phone') || ''), industry: String(data.get('industry')), packaging_requirement: String(data.get('packaging_requirement')), message: String(data.get('message')), website: String(data.get('website') || ''), submission_key: key.current } }); setState('success'); } catch (err) { setState('error'); setError(err instanceof Error ? err.message : 'Your enquiry could not be saved. Please try again.'); } }
 if (state === 'success') return <div className="contact-success" role="status"><Check size={40}/><div className="eyebrow">CONVERSATION STARTED</div><h2>Thank you for<br/>reaching out.</h2><p>Your enquiry has been received by Aurestem.</p><Button variant="outline" className="action" onClick={() => { key.current=''; setState('idle'); }}>Send another enquiry <ArrowUpRight/></Button></div>;
 return <form className="contact-form" onSubmit={submit}><div className="form-grid">{[['name','Name','text','name'],['company','Company','text','organization'],['country','Country','text','country-name'],['email','Email','email','email'],['phone','Phone','tel','tel']].map(([name,label,type,auto]) => <div className="field" key={name}><label htmlFor={name}>{label}{name !== 'phone' && <span> *</span>}</label><input id={name} name={name} type={type} autoComplete={auto} required={name !== 'phone'} minLength={name==='email' || name==='phone' ? undefined : 2} maxLength={name==='email' ? 254 : 120}/></div>)}<div className="field"><label htmlFor="industry">Industry *</label><select id="industry" name="industry" required defaultValue=""><option disabled value="">Select your industry</option>{['Fresh Produce','Agriculture','Food Exporters','Retail','Food Distribution','Cold Chain','Packhouses','Other'].map(x => <option key={x}>{x}</option>)}</select></div><div className="field full"><label htmlFor="packaging_requirement">Packaging requirement *</label><input id="packaging_requirement" name="packaging_requirement" required minLength={2} maxLength={500}/></div><div className="field full"><label htmlFor="message">Message *</label><textarea id="message" name="message" rows={4} required minLength={10} maxLength={5000}/></div></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>{error && <p role="alert" className="form-error">{error}</p>}<div className="form-bottom"><p>Your details will only be used to respond to your enquiry.</p><Button className="action" disabled={state==='sending'} type="submit">{state==='sending' ? 'Sending enquiry…' : 'Start a Conversation'}<ArrowUpRight/></Button></div></form>;
}
