import { createFileRoute } from '@tanstack/react-router';
import { PageIntro, Photo, TextLink, CTASection, images, meta } from '@/components/aurestem/shared';
export const Route = createFileRoute('/industries')({ head: () => meta('Industries and supply chains', 'Packaging approaches for fresh produce, agriculture, exporters, retail, distribution, cold chain and packhouses.'), component: Industries });
const industries = [
 ['Fresh Produce','Protecting the quality of living products.','Delicate produce, respiration and moisture changes.','Produce-specific films and formats that support a balanced packaging environment.',images.produce],
 ['Agriculture','Better protection starts at the source.','Quality variation and the transition from harvest to packing.','Packaging selection informed by crop requirements and post-harvest handling.',images.exportsPhoto],
 ['Food Exporters','Freshness across borders.','Long transit times and changing transport conditions.','Packaging systems considered alongside export cartons, transit time and destination needs.',images.exportsPhoto],
 ['Retail','Presenting freshness. Protecting quality.','Product visibility, handling and time on shelf.','Clear packaging approaches that consider presentation, protection and material efficiency.',images.produce],
 ['Food Distribution','Consistency through every handover.','Multiple handling stages and distribution environments.','Practical formats developed around the demands of storage and distribution.',images.packhouse],
 ['Cold Chain','Packaging that works with temperature control.','Condensation and temperature transitions.','Moisture and gas-exchange behaviour evaluated within relevant cold-chain conditions.',images.material],
 ['Packhouses','Intelligent materials. Practical integration.','Throughput, packing-line compatibility and consistent quality.','Material and format selection designed around existing equipment and operational requirements.',images.packhouse],
];
function Industries() { return <><PageIntro label="INDUSTRIES" title="One fresh ambition. Every link in the chain.">From the grower to the final destination, we consider packaging in the context of the people, processes and conditions it serves.</PageIntro><section className="container industry-list">{industries.map(([name,desc,challenge,approach,image],i) => <article className={`industry-section ${i%2 ? 'reverse' : ''}`} key={name}><Photo src={image} alt={`${name} packaging application`}/><div><div className="eyebrow">0{i+1} / {name.toUpperCase()}</div><h2>{name}.</h2><p className="industry-lead">{desc}</p><dl><dt>THE CHALLENGE</dt><dd>{challenge}</dd><dt>OUR APPROACH</dt><dd>{approach}</dd></dl><TextLink to="/contact">Discuss your application</TextLink></div></article>)}</section><CTASection/></>; }
