import { createFileRoute } from '@tanstack/react-router';
import { PageIntro, SolutionModule, CTASection, images, meta } from '@/components/aurestem/shared';
export const Route = createFileRoute('/solutions')({ head: () => meta('Packaging solutions', 'Application-led packaging for fresh produce, export supply chains and next-generation materials.'), component: Solutions });
function Solutions() { return <><PageIntro label="SOLUTIONS" title="The right packaging. For every journey.">Different produce. Different conditions. One considered approach: packaging designed around the needs of your product.</PageIntro><section className="container"><SolutionModule index="01" title="Fresh produce." description="From delicate berries and grapes to tomatoes, avocados and leafy vegetables, produce has distinct respiration and moisture requirements. We consider those requirements when selecting packaging films and formats to support freshness management." image={images.produce} alt="Berries, grapes and tomatoes surrounded by transparent packaging" tags={['Produce-specific gas exchange','Moisture management','Material efficiency']}/><SolutionModule index="02" title="Export packaging." description="Longer journeys ask more of packaging. We consider transit time, handling conditions, temperature and existing carton systems to develop approaches for growers and exporters moving produce to distant markets." image={images.exportsPhoto} alt="Packaged grapes in neatly aligned export cartons" tags={['Carton and liner systems','Transit protection','Supply-chain compatibility']}/><SolutionModule index="03" title="Material solutions." description="Material selection begins with application requirements. Bio-based and engineered film approaches are evaluated for their barrier behaviour, process compatibility and resource efficiency — without compromising the role packaging must perform." image={images.material} alt="Folded translucent material film showing its thin structure" tags={['Bio-based material selection','Engineered film structures','Performance-led development']}/></section><ProductRange/><section className="process-section container"><div className="eyebrow">A CONSIDERED DEVELOPMENT PROCESS</div><h2>Built around your requirements.</h2><div className="process-grid">{[['01','Understand','Your produce, packing process and destination conditions.'],['02','Engineer','Material behaviour and packaging format matched to the application.'],['03','Evaluate','Testing in relevant conditions to inform the right approach.']].map(([n,t,d]) => <div key={n}><span className="eyebrow">{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><CTASection/></>; }

const range: [string, string, string, string[], string][] = [
 ['01','Compostable packaging for global fresh produce supply chains','Compostable packaging solutions for fresh produce exports, helping maintain freshness from harvest to destination. Transparent. Compostable. Proven.',['Compatible with existing operations','Reduced moisture loss','Reduced condensation','Export ready'],'Bananas · Grapes · Pomegranates · Leafy greens · Citrus · Exotics'],
 ['02','Keeping fresh-cut produce fresher for longer','Innovative packaging for fresh-cut fruits and vegetables.',['Helps maintain freshness at ambient conditions','Supports shelf-life extension','Reduces food waste','Sustainable packaging alternative'],'Fresh-cut fruits · Vegetables'],
 ['03','Crystal clear. Compostable. Sustainable.','Next-generation retail packaging for fresh produce.',['Premium shelf appeal','Maintains produce freshness','Reduced fogging and condensation','Easy integration with existing packing lines'],'Fresh produce · Fruits · Vegetables'],
 ['04','Compostable packaging for frozen foods','Designed for performance in frozen storage and distribution.',['Suitable for frozen storage conditions','Sustainable alternative to conventional plastic packaging'],'Frozen vegetables · Ready-to-cook foods'],
 ['05','Smart packaging for meat','Designed to support product quality from processing to consumption.',['Suitable for cold chain operations','Compostable packaging solution'],'Meat · Poultry'],
 ['06','Soft. Fresh. Sustainable.','Next-generation compostable packaging for bakery products.',['Helps maintain freshness and texture','Sustainable alternative to conventional packaging'],'Bread · Bakery products'],
 ['07','The future of milk packaging','Compostable pouch formats developed for dairy.',['Sustainable alternative to conventional pouches'],'Milk · Dairy'],
 ['08','Compostable packaging for everyday essentials','Sustainable solutions for retail, grocery and food packaging.',['Compostable alternative to conventional plastics','Strong, durable and consumer-friendly','Designed for modern retail and supply chains'],'Rice and grain packaging · Grocery rolls · Retail packaging'],
];
function ProductRange() { return <section className="container" style={{ paddingBlock: 'clamp(4rem,9vw,8rem)' }}><div className="eyebrow">AURESTEM × PEELON — SUSTAINABLE PACKAGING FOR THE FUTURE</div><h2 style={{ fontSize: 'clamp(2.2rem,6vw,5rem)', lineHeight: 1, letterSpacing: '-0.04em', maxWidth: '14ch', margin: '1.5rem 0 3rem' }}>Less waste. More freshness.</h2><div>{range.map(([n,t,d,pts,apps]) => <article key={n} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))', gap: '1.5rem 3rem', borderTop: '1px solid var(--border)', padding: '2.5rem 0' }}><div><span className="eyebrow">{n}</span><h3 style={{ fontSize: 'clamp(1.5rem,2.6vw,2.2rem)', lineHeight: 1.1, letterSpacing: '-0.02em', marginTop: '.75rem' }}>{t}</h3></div><div><p>{d}</p><ul style={{ margin: '1.25rem 0', paddingLeft: '1.1rem', listStyle: 'square' }}>{pts.map(x => <li key={x}>{x}</li>)}</ul><p className="eyebrow">APPLICATIONS — {apps}</p></div></article>)}</div></section>; }
